# Generated by Django 2.0.3 on 2018-04-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_roll',
            field=models.IntegerField(),
        ),
    ]
