# Generated by Django 2.0.3 on 2018-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180412_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='candidate_name',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
