# Generated by Django 2.0.3 on 2018-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_voter_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
