# Generated by Django 2.0.3 on 2018-04-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180413_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_username',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
