# Generated by Django 2.0.3 on 2018-04-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180413_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voterdetails',
            options={'verbose_name': 'Voter Details', 'verbose_name_plural': 'Voter Details'},
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='candidate_voted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Candidate'),
        ),
    ]
