# Generated by Django 2.0.3 on 2018-04-13 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180413_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterdetails',
            name='candidate_voted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Candidate'),
        ),
    ]
