# Generated by Django 2.0.3 on 2018-04-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180413_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterdetails',
            name='candidate_voted',
        ),
    ]
