# Generated by Django 2.0.3 on 2018-04-13 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_voterdetails_candidate_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterdetails',
            name='voter_roll',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voterdetails',
            name='candidate_voted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Candidate'),
        ),
    ]
